### ISSUE TITLE
Confusing calendar navigation

### ISSUE THREAD

**Issue by AniaSzlkwcz** [wpappointments/wpappointments#186]
The navigation feels confusing when it's navigating between the months, but has "today" in the middle.
![obraz](https://github.com/wpappointments/wpappointments/assets/66020772/72e01601-3a93-463c-a25a-e59b305ced98)
Feels like a user is navigating between days and not months. 
Note that similar solutions put "today" option on the side, and navigation near the month name indicating what it regards.

**Comment by dawidurbanski** [comment]
This was taken from Apple Calendar:

![CleanShot 2024-03-18 at 03 05 07@2x](https://github.com/wpappointments/wpappointments/assets/12466568/caa853cb-4735-4227-a782-88c4b0b17b06)

We may rethink this when doing calendar view page redesign.

For reference, google calendar:

![CleanShot 2024-03-18 at 03 06 04@2x](https://github.com/wpappointments/wpappointments/assets/12466568/39c8f58e-7480-4166-b209-14f26d5e4602)

Notion calendar:

![CleanShot 2024-03-18 at 03 06 32@2x](https://github.com/wpappointments/wpappointments/assets/12466568/27191f47-20eb-4600-8007-9eb6bc8d5113)

Calendar:

![CleanShot 2024-03-18 at 03 07 51@2x](https://github.com/wpappointments/wpappointments/assets/12466568/e71abf2d-a7c4-4571-8397-165e8ef2a512)

Looks like majority uses the proposed solution.

I'm going to close this issue, since we are going to do the calendar view overhaul.
